Repository clue/framework-x, pull requests merged in 2021-11, with the labels that each got.

#64 Prepare public beta
  README.md
  composer.json
  docs/README.md
  docs/best-practices/deployment.md
  docs/getting-started/community.md
  docs/getting-started/quickstart.md
  mkdocs.yml
Labels: maintenance, new feature

#72 Remove unused import and fix typo
  docs/best-practices/controllers.md
  tests/FilesystemHandlerTest.php
Labels: bug, maintenance

#81 Improve documentation, remove leftover `$loop` references
  docs/async/coroutines.md
  docs/async/fibers.md
  docs/async/promises.md
  docs/integrations/database.md
Labels: bug, easy pick, maintenance

#83 Typo correction of fibers/coroutines in FAQ
  docs/async/coroutines.md
Labels: bug, easy pick, maintenance

#82 Add Caddy to deployment docs
  docs/best-practices/deployment.md
Labels: maintenance, new feature

#87 Add documentation for manual restart of systemd service
  docs/best-practices/deployment.md
Labels: maintenance, new feature

#88 Simplify `App` by always using default loop, drop optional loop instance
  src/App.php
  tests/AppTest.php
Labels: new feature, BC break

#89 Accept class names instead of callables (DI container preparation)
  docs/api/app.md
  docs/api/middleware.md
  docs/best-practices/controllers.md
  src/App.php
  src/RouteHandler.php
  tests/AppTest.php
  tests/MiddlewareHandlerTest.php
  tests/RouteHandlerTest.php
Labels: new feature
