Repository clue/framework-x, pull requests merged in 2022-10, with the labels that each got.

#194 Test on PHP 8.2 and update test environment
  .github/workflows/ci.yml
  phpunit.xml.dist
Labels: new feature

#191 Respect explicit response status code when `Location` response header is given (PHP SAPI)
  examples/index.php
  src/Io/SapiHandler.php
  tests/acceptance.sh
Labels: bug

#199 Update test environment to report failed assertions
  .github/workflows/ci.yml
  phpunit.xml.dist
  phpunit.xml.legacy
Labels: maintenance

#200 Add PHPStan to test environment
  .gitattributes
  .github/workflows/ci.yml
  composer.json
  examples/index.php
  phpstan.neon.dist
  src/App.php
  src/Container.php
  src/ErrorHandler.php
  src/Io/FiberHandler.php
  src/Io/RouteHandler.php
  src/Io/SapiHandler.php
  tests/AccessLogHandlerTest.php
  tests/AppTest.php
  tests/ContainerTest.php
  tests/ErrorHandlerTest.php
  tests/Fixtures/InvalidConstructorInt.php
  tests/Fixtures/InvalidConstructorIntersection.php
  tests/Fixtures/InvalidConstructorSelf.php
  tests/Fixtures/InvalidConstructorUnion.php
  tests/Fixtures/InvalidConstructorUnknown.php
  tests/Fixtures/InvalidConstructorUntyped.php
  tests/Io/FiberHandlerTest.php
  tests/Io/RouteHandlerTest.php
  tests/Io/SapiHandlerTest.php
Labels: maintenance

#201 Improve type definitions and update to PHPStan level `max`
  examples/index.php
  phpstan.neon.dist
  src/AccessLogHandler.php
  src/App.php
  src/Container.php
  src/ErrorHandler.php
  src/FilesystemHandler.php
  src/Io/FiberHandler.php
  src/Io/HtmlHandler.php
  src/Io/MiddlewareHandler.php
  src/Io/RedirectHandler.php
  src/Io/RouteHandler.php
  src/Io/SapiHandler.php
  tests/AccessLogHandlerTest.php
  tests/AppMiddlewareTest.php
  tests/AppTest.php
  tests/ContainerTest.php
  tests/ErrorHandlerTest.php
  tests/FilesystemHandlerTest.php
  tests/Io/FiberHandlerTest.php
  tests/Io/HtmlHandlerTest.php
  tests/Io/MiddlewareHandlerTest.php
  tests/Io/RedirectHandlerTest.php
  tests/Io/RouteHandlerTest.php
  tests/Io/SapiHandlerTest.php
Labels: maintenance
