Repository clue/framework-x, pull requests merged in 2022-03, with the labels that each got.

#124 Add instructions for authorization header under Apache
  docs/best-practices/deployment.md
  examples/apache/.htaccess
Labels: documentation

#125 Add contribution instructions to `README.md`
  README.md
Labels: documentation

#126 Improve documentation for routing HTTP `HEAD` requests
  docs/api/app.md
  examples/index.php
  tests/acceptance.sh
Labels: documentation

#127 Add support / sponsorship info
  .github/FUNDING.yml
  README.md
  tests/FilesystemHandlerTest.php
Labels: maintenance, documentation

#128 Add fiber compatibility mode for PHP < 8.1
  .github/workflows/ci.yml
  docs/async/fibers.md
  examples/index.php
  src/App.php
  tests/AppTest.php
  tests/acceptance.sh
Labels: new feature

#129 Fix invalid link to PHP documentation
  docs/api/response.md
Labels: easy pick, documentation

#131 Improve error output for exception messages with special characters
  examples/index.php
  src/HtmlHandler.php
  tests/AppTest.php
  tests/ErrorHandlerTest.php
  tests/HtmlHandlerTest.php
Labels: new feature
