Repository clue/framework-x, pull requests merged in 2022-04, with the labels that each got.

#136 Add instructions for Docker containers
  docs/best-practices/deployment.md
Labels: documentation

#148 Update integration tests to install Framework X as dependency
  .github/workflows/ci.yml
  examples/apache/index.php
  examples/index.php
  examples/nginx/nginx.conf
  examples/nginx/public/index.php
  phpunit.xml.dist
  phpunit.xml.legacy
  tests/install-as-dep/.gitignore
  tests/install-as-dep/composer.json
  tests/install-as-dep/public/index.php
Labels: maintenance

#149 Add tests for `Dockerfile` instructions
  .github/workflows/ci.yml
  tests/Dockerfile-basics
  tests/Dockerfile-production
Labels: maintenance

#150 Add signal handling support for `SIGINT` and `SIGTERM`
  src/App.php
  tests/AppTest.php
Labels: new feature

#151 Update recommended `Dockerfile` instructions to run as PID 1
  docs/best-practices/deployment.md
  tests/Dockerfile-production
Labels: documentation

#153 Add missing `)` in example
  docs/async/promises.md
Labels: documentation

#154 Minor documentation improvements
  docs/async/coroutines.md
  docs/best-practices/deployment.md
Labels: documentation

#138 Add instructions for HTTP redirecting
  docs/api/app.md
  docs/api/response.md
Labels: documentation
