Repository clue/framework-x, pull requests merged in 2022-02, with the labels that each got.

#113 Update to improve protocol handling for HTTP responses with no body
  composer.json
  tests/acceptance.sh
Labels: bug, new feature

#115 Update README.md
  README.md
Labels: documentation

#116 Update installation instructions for react/async development version
  docs/async/fibers.md
Labels: documentation

#117 Automatically start new fiber for each request on PHP 8.1+
  composer.json
  examples/index.php
  src/App.php
  src/FiberHandler.php
  tests/AppMiddlewareTest.php
  tests/AppTest.php
  tests/FiberHandlerTest.php
  tests/acceptance.sh
Labels: new feature

#118 Improve fiber tests to avoid now unneeded `await()` calls
  tests/AppTest.php
  tests/FiberHandlerTest.php
Labels: maintenance
